services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  ai:
    build: ./ai
    ports:
      - "5000:5000"
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - ./mongo-data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
